version: '3'
services:
  web:
    build: .
    command: yarn run dev
    ports:
      - "8082:8080"
    volumes:
      - .:/usr/src/app
    networks:
      rndevoo_network:
        aliases:
          - logging
    env_file: .env

networks:
  rndevoo_network:
    external:
      name: rndevoo_network
